### ISSUE TITLE
expo export fails when exporting android

### ISSUE THREAD

**Issue by cryptixcoder** [expo/expo-cli#110]
Just upgraded to expo-cli version 2.2.1 and created a new project using 
```
expo init myProject 
```
I then tried to export using
```
expo eject 
```
When it gets to exporting the android version it fails with the following error:

```
[13:07:49] spawn ../../tools-public/check-dynamic-macros-android.sh ENOENT
[13:07:49] Error: spawn ../../tools-public/check-dynamic-macros-android.sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by esamelson** [comment]
Hi @cryptixcoder - thanks for the report. We'll work on getting a new version out soon that fixes this. In the meantime you'll need to downgrade to 2.2.0 in order to eject on Android.

**Comment by cryptixcoder** [comment]
@esamelson I downgraded and tried to create a new project and still getting the same error.

**Comment by esamelson** [comment]
@cryptixcoder could you run `expo --version` to verify you downgraded correctly?

**Comment by cdgugler** [comment]
Same issue here. Downgraded to 2.2.0, `expo --version` shows 2.2.0, same error.

**Comment by esamelson** [comment]
Sorry about this, everyone! I've just published `expo-cli@2.2.2` which should fix this issue.

**Comment by funkjunky** [comment]
This did not fix my issue, but mine may be a different issue. I'll open up a unique issue.

**Comment by cdgugler** [comment]
Confirmed, 2.2.2 Ejected successfully. Thanks!

**Comment by cryptixcoder** [comment]
Confirmed. Thanks!

**Comment by fwal** [comment]
Also getting this exact error when using `turtle-cli@0.3.3` on sdk31

**Comment by dsokal** [comment]
Let's move the discussion about `turtle-cli` here - https://github.com/expo/expo/issues/2715
