### ISSUE TITLE
Bundles stuck on 99% if previous build attempt contained syntax error - Or does not build at all

### ISSUE THREAD

**Issue by Slapbox** [expo/expo-cli#184]
## Description

The bundler tries using old versions of the code after changes are made, showing syntax errors which were resolved. It does try to build, so it knows the file was updated, but it keeps the old, broken code for its build attempt.

To reproduce: Write some code with a syntax error and then fix it. I can press `R` and `Shift+R` all you want, but 99% is as far as it goes without restarting expo entirely.

This seems to be the same issue reported here: https://github.com/react-community/create-react-native-app/issues/560

## Expected Behavior

Build completes when input code is valid.

## Observed Behavior

Changes to files are noticed and rebuild is attempted, but the code continues to fail to build, showing syntax errors which were corrected already. Pressing `Shift+R` gets the bundler to try to rebuild, but it gets stuck at 99% if the previous input code was invalid.

## Environment

 Expo CLI 2.4.0 environment info:
   System:
     OS: Windows 7
   Binaries:
     Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
     npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

 Diagnostics report:
   https://exp-xde-diagnostics.s3.amazonaws.com/slapbox-0218467b-abe6-470d-ac38-a9a8ff0a2baa.tar.gz

Also specify:
- Pixel 2, Android 9

**Comment by thomashagstrom** [comment]
Confirmed. This is making development extremely slow. Occurs after the new expo cli

**Comment by Slapbox** [comment]
@thomashagstrom can you post the output of running `expo diagnostics` and the device/emulator you're testing with so we can increase the odds of getting this resolved?

**Comment by thomashagstrom** [comment]
@Slapbox Sure. Here's one after changing networks.

```ERROR
08:58
Error running `xcrun simctl openurl booted exp://127.0.0.1:19000`: An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=60):
The operation couldn’t be completed. Operation timed out
Operation timed out
ERROR
08:58
Error installing or running app. Error: Process exited with non-zero code: 60```

**Comment by thomashagstrom** [comment]
@Slapbox here's a common example, where syntax was wrong and Expo is unable to recover even with Command + R reloading.

iOS simulator states
> DownloadingJavaScript bundle 100,00%

```0] You are now debugging remotely; check your browser console for your application logs.
[14:26:32] SyntaxError: /Users/.../build/about/AboutScreen.js: Unexpected token (9:54)
[14:26:32]    7 |     render() {
[14:26:32]    8 |         return (React.createElement(View, { style: { padding: 20 } },
[14:26:32] >  9 |             React.createElement(ScrollView, { style:  >
[14:26:32]      |                                                       ^
[14:26:32]   10 |                     (React.createElement(CrossLabel, null, "L\u00E5t some text")
[14:26:32]   11 |                         ,
[14:26:32]   12 |                             (React.createElement(CrossLabel, null, "some other text f\u00E5.")
[14:26:32] Failed building JavaScript bundle.
```

Doing "run on simulator" does nothing:
> Opening exp://127.0.0.1:19000 in iOS simulator
No effect

**Comment by Slapbox** [comment]
@thomashagstrom I agree it's definitely an issue. If possible you should include the output of running `expo diagnostics`.

My one report is a data point, but two is a pattern that greatly increases the odds this gets fixed, even if the odds remain low with just the two of us reporting it.

**Comment by Brandons42** [comment]
I'm having the same issue. The development process is severely worsened. At times it makes Expo unusable.

**Comment by Slapbox** [comment]
@Brandons42 if possible could you include the output of running `expo diagnostics`?

**Comment by nicotroia** [comment]
Just started getting this error out of nowhere, was working last night:

`expo diagnostics`
There is a new version of expo-cli available (2.6.13).
You are currently using expo-cli 2.6.0
Run `npm install -g expo-cli` to get the latest version

  Expo CLI 2.6.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10L213o - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.0 => 30.0.1
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4
      react-navigation: ^2.13.0 => 2.18.0
    npmGlobalPackages:
      expo-cli: 2.6.0

**Comment by YKSing** [comment]
same issue here

**Comment by andreychernih** [comment]
Having a similar problem with expo stuck after syntax error:

```
[08:13:09] SyntaxError: (redacted)/App.js: Unexpected token, expected "{" (5:0)
[08:13:09]
[08:13:09]   3 |
[08:13:09]   4 | import
[08:13:09] > 5 | import stateStore from 'state-store';
[08:13:09]     | ^
[08:13:09]   6 |
[08:13:09]   7 | export default class App extends React.Component {
[08:13:09]   8 |   render() {
Building JavaScript bundle [                                                                                                    ] 0%
```

Diagnostics:

```
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.6.2 - /usr/local/bin/zsh
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.6.14
```

**Comment by cooperbrown9** [comment]
Same issue! Please fix!!! 
So frustrating, only way to fix is to completely close the expo app on simulator and then reopen it.
Only happens sometimes tho...very peculiar issue

**Comment by maasantos10** [comment]
guys, any idea about this problem? I try to create a project and I got the same error.

**Comment by Brandons42** [comment]
After experiencing this issue a few times, it seems as though this issue only occurs if there's an error in your application when you start up the development server(if there's an error when you run "expo/yarn/npm start").

**Comment by Slapbox** [comment]
@Brandons42 in my experience it occurs any time there's an error in your code which isn't corrected before the build process fails. 

So if you make a typo, save, quickly correct it, and save again you can usually avoid it. If you make a typo, save, and the build hits the error before you correct it, I have to end the script 99.9% of the time and run `expo start` again.

**Comment by mirague** [comment]
Also seeing this, however it gets stuck on 0% often after a syntax error:

```
  Expo CLI 2.10.0 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.16.0 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 2.10.0
```

**Comment by nickparkin** [comment]
Also seeing this across two Macs even after upgrading. Any solution?

**Comment by brettdh** [comment]
Same.

```
➜ expo diagnostics
There is a new version of expo-cli available (2.11.6).
You are currently using expo-cli 2.10.1
Run `npm install -g expo-cli` to get the latest version

  Expo CLI 2.10.1 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 5.10.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4408382
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.3.10 => 3.4.11 
      expo: ^31.0.4 => 31.0.4 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz => 0.57.1 
      react-navigation: ^3.0.5 => 3.0.5 
    npmGlobalPackages:
      expo-cli: 2.10.1
```

**Comment by elizamaria** [comment]
Same for me :(

  Expo CLI 2.11.8 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: yarn install v0.19.1
      npm: 5.5.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.4.1 => 3.4.1
    npmGlobalPackages:
      expo-cli: 2.11.8

**Comment by Slapbox** [comment]
I wonder if all the times I've seen this were related to a `require` or `import` issue. I don't think so, but it's possible. It would make more sense that that would break the packager than other syntax errors.

**Comment by elizamaria** [comment]
This is an issue that also happens on imports when doing a RN project without expo, so it's probably related to something else.

**Comment by napalm272** [comment]
Any updates on this?

**Comment by lukejsimonetti** [comment]
Same. 0% build on syntax error. 

`Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: yarn install v0.24.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.39s. - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.14.0`

**Comment by dominicgan** [comment]
Same. 0% build on syntax error.
```
 Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.0.3 - /usr/local/bin/bash
    Binaries:
      Node: 9.10.0 - ~/.nvm/versions/node/v9.10.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v9.10.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v9.10.0/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.6.1
    npmGlobalPackages:
      expo-cli: 2.14.0
```

**Comment by RichMatthews** [comment]
this is seriously irritating and slowing down development considerably. please can this be resolved asap

**Comment by mostlyerror** [comment]
Is there a previous stable version of expo that we can revert to while this issue remains?

**Comment by ofilipowicz** [comment]
> Is there a previous stable version of expo that we can revert to while this issue remains?

Honestly I remember it happens since I started using Expo when it's just been published.

**Comment by Slapbox** [comment]
@mostlyerror - Expo 30 MIGHT not have been affected, or I might just not have seen it.

**Comment by StevenZiu** [comment]
still no update?????

**Comment by StevenZiu** [comment]
come across this issue anytime the syntax error happens

**Comment by r1csu** [comment]
The same, spent days only with the issue, impossible to get further with the development as it's taking all the time to just stop and start expo again.

**Comment by superandrew** [comment]
same here

**Comment by SuiGeneris01** [comment]
The issue should be fixed as soon as possible, there is should be a way to work around making changes while bundling js.

**Comment by RichMatthews** [comment]
gone back to being a react developer as this was too painful

**Comment by mabbas64** [comment]
Happening for me on Windows 10 x64 with latest expo version as well :(

**Comment by Chenart** [comment]
Happening to me too!

**Comment by ziishaned** [comment]
I solved the issue by closing `react-native-debugger`

**Comment by Flooorent** [comment]
I had the same issue. I fixed it by switching from **Live Reload** to **Hot Reload**.

**Comment by AmmarMZ** [comment]
> I solved the issue by closing `react-native-debugger`

@ziishaned how can I do this? Running on Android.

> I had the same issue. I fixed it by switching from **Live Reload** to **Hot Reload**.

@Flooorent how can I do this? Running on Android.

**Comment by Flooorent** [comment]
@AmmarMZ If you shake your device a new menu should appear with multiple buttons. You should have `Disable Live Reload` and `Hot Reloading Unavailable`. First click on `Disable Live Reload`. Shake your device again. You should have now `Enable Live Reload` and `Enable Hot Reloading`. Click on `Enable Hot Reloading`. You're done :)

**Comment by AmmarMZ** [comment]
> @AmmarMZ If you shake your device a new menu should appear with multiple buttons. You should have `Disable Live Reload` and `Hot Reloading Unavailable`. First click on `Disable Live Reload`. Shake your device again. You should have now `Enable Live Reload` and `Enable Hot Reloading`. Click on `Enable Hot Reloading`. You're done :)
> 
> NB: I use an iPhone so I'm not 100% sure this is the same with an android.

It worked! Thanks so much

**Comment by Flooorent** [comment]
My pleasure !

**Comment by superandrew** [comment]
I notice that in general this issue is resolved temporarily by: 
1. closing react native debugger 
2. killing the expo app from the phone/emulator and of course 
3. restarting the expo client. 
This issue keeps returning on every compilation time error though

**Comment by kousun12** [comment]
+1 I'm usually getting back on track by quitting the simulator, quitting RN Debugger, killing the packager, restart the packager, run ios, cmd + D -> turn off remote debugging, open RN Debugger, cmd + D -> start remote debugging. 

i'm now super gun shy about saving, or switching windows because i know it's inevitable that there's working code that might not compile and i have to jump these hoops all over again

**Comment by quakig** [comment]
This error persists even one year after the original poster wrote about it. 

Strangely no resolutions provided for such a vital issue that makes development virtually impossible :(

**Comment by fson** [comment]
The changes made to logging (related to SDK 36 support) in https://github.com/expo/expo-cli/pull/1183 might also address this issue.

**Comment by haikyuu** [comment]
@fson i still get the error after installing the lsat version (that includes the PR). Extremely disapointing ...

**Comment by pmgou** [comment]
im using `$ adb shell pm clear host.exp.exponent` to clear the data from expo.. but doesn't work all the time... it's annoying

**Comment by brentvatne** [comment]
the original reported issue was a problem with metro bundler that has been resolved. closing and locking this issue for that reason.

if you have some other seemingly related issues please open a new issue and provide us with your reproducible steps as per the issue template. thanks!
