### ISSUE TITLE
Allow expo export to run offline

### ISSUE THREAD

**Issue by skidr0w** [expo/expo-cli#230]
## Description

`expo export` requires an expo login. This is a problem when running export on a CI server, which has limited internet connectivity.

## Expected Behavior

I expected `expo export` to not require an expo login. 

## Observed Behavior

When i run `expo export` without login and limited internet connectivity, the process failes with

```
[14:18:12] Files successfully saved.
[14:18:12] An Expo user account is required to proceed.
[14:18:12] Not logged in. Use `expo login -u username -p password` to log in.
```

Can someone please explain, why `expo login` is needed for exporting the Javascript Bundle data? It would really help, if this is not mandatory. It would make expo useable in enterprise companies, which have CI servers without internet connection.

**Comment by fson** [comment]
Thanks for reporting this issue. `expo export` previously used authentication to include the username in the `id` field in the exported manifest. This has now been fixed in `expo-cli@2.6.4`, and if you're logged out, the string `anonymous` will be used instead of the username.

**Comment by skidr0w** [comment]
@fson I'd like to reopen this issue. `expo export` does still not work offline. The error message is now:

```
[12:45:31] Warning: Problem validating app.json: Unable to perform cache refresh for /root/.cache/expo/schema-32.0.0.json: Error: Request failed with status code 501.
[12:45:31] Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 7.0.0, 8.0.0, 9.0.0
[12:45:31] Unable to find an existing Expo CLI instance for this directory, starting a new one...
[12:45:31] Exporting your app...
[12:45:31] Warning: Problem validating app.json: Unable to perform cache refresh for /root/.cache/expo/schema-32.0.0.json: Error: Request failed with status code 501.
[12:45:31] Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 7.0.0, 8.0.0, 9.0.0
[12:45:35] Starting Metro Bundler on port 19001.
[12:45:42] fs.js:1384
[12:45:42]     throw error;
[12:45:42]     ^
[12:45:42] 
[12:45:42] Error: watch /app/npm-cache/_cacache/index-v5/ea/26 ENOSPC
[12:45:42]     at FSWatcher.start (fs.js:1382:19)
[12:45:42]     at Object.fs.watch (fs.js:1408:11)
[12:45:42]     at NodeWatcher.watchdir (/app/node_modules/sane/src/node_watcher.js:175:20)
[12:45:42]     at Walker.<anonymous> (/app/node_modules/sane/src/common.js:116:12)
[12:45:42]     at emitTwo (events.js:126:13)
[12:45:42]     at Walker.emit (events.js:214:7)
[12:45:42]     at /app/node_modules/walker/lib/walker.js:69:16
[12:45:42]     at go$readdir$cb (/app/node_modules/graceful-fs/graceful-fs.js:162:14)
[12:45:42]     at FSReqWrap.oncomplete (fs.js:135:15)
[12:45:48] Metro Bundler is not running. Trying to restart it...
[12:45:49] Starting Metro Bundler on port 19001.
[12:45:49] Your JavaScript transform cache is empty, rebuilding (this may take a minute).
[12:45:50] Building iOS bundle
[12:45:57] fs.js:1384
[12:45:57]     throw error;
[12:45:57]     ^
[12:45:57] 
[12:45:57] Error: watch /app/npm-cache/_cacache/index-v5/ea/1d ENOSPC
[12:45:57]     at FSWatcher.start (fs.js:1382:19)
[12:45:57]     at Object.fs.watch (fs.js:1408:11)
[12:45:57]     at NodeWatcher.watchdir (/app/node_modules/sane/src/node_watcher.js:175:20)
[12:45:57]     at Walker.<anonymous> (/app/node_modules/sane/src/common.js:116:12)
[12:45:57]     at emitTwo (events.js:126:13)
[12:45:57]     at Walker.emit (events.js:214:7)
[12:45:57]     at /app/node_modules/walker/lib/walker.js:69:16
[12:45:57]     at go$readdir$cb (/app/node_modules/graceful-fs/graceful-fs.js:162:14)
[12:45:57]     at FSReqWrap.oncomplete (fs.js:135:15)
[12:45:57] socket hang up
[12:45:57] Set EXPO_DEBUG=true in your env to view the stack trace.
The command '/bin/sh -c expo export -p https://example.com/' returned a non-zero code: 1
script returned exit code 1
```

It seems like xdl does not bundle the schema for Expo SDK 32.
