### ISSUE TITLE
Misleading error message expo-cli

### ISSUE THREAD

**Issue by mschipperheyn** [expo/expo-cli#2455]
### Summary of Issue 

I just spent a few hours trying to figure out why my docker web build kept throwing `Failed to read config at: /app/app.config.js`
TDLR installed dependencies with NODE_ENV production. I should have installed with NODE_ENV development and afterwards set NODE_ENV to production when I run the expo build comand.

I had to mount the docker container and manually hack a console.log into the getConfig.js to finally understand the obvious issue: missing development dependencies.

The issue: expo should output the actual error, instead of sugar coating it with a nice message or do both.

**Comment by brentvatne** [comment]
can you try rephrase this? I don't understand

**Comment by mschipperheyn** [comment]
Can I share a docker file that reproduces the issue?

```
FROM node:12.18.2-alpine AS builder

ARG targetEnvironment

RUN echo "environment:"
RUN echo $targetEnvironment

ENV NODE_VERSION 12.18.2
ENV YARN_VERSION 1.22.4

RUN apk add --no-cache --virtual .build-deps-yarn curl \
    && curl -fSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" \
    && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ \
    && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn \
    && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg \
    && rm yarn-v$YARN_VERSION.tar.gz \
    && apk del .build-deps-yarn
RUN apk add --no-cache --virtual build-dependencies \
    python \
    make \
    g++

RUN apk update && apk add git

RUN npm install -g expo-cli --allow-root --unsafe-perm=true 

WORKDIR /app
COPY . /app

ENV NODE_ENV production
RUN for attempt in $(seq 1 100); do yarn install --ignore-scripts --frozen-lockfile --ignore-optional && break; done
RUN npm rebuild

RUN expo build:web --no-pwa

# Deployment image
FROM nginx:1.19.1

LABEL version = "App server"

COPY --from=builder /app/web-build /usr/share/nginx/html

EXPOSE 80
EXPOSE 443

```

It should be 

```
FROM node:12.18.2-alpine AS builder

ARG targetEnvironment

RUN echo "environment:"
RUN echo $targetEnvironment

ENV NODE_VERSION 12.18.2
ENV YARN_VERSION 1.22.4

RUN apk add --no-cache --virtual .build-deps-yarn curl \
    && curl -fSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" \
    && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ \
    && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn \
    && ln -snf /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg \
    && rm yarn-v$YARN_VERSION.tar.gz \
    && apk del .build-deps-yarn
RUN apk add --no-cache --virtual build-dependencies \
    python \
    make \
    g++

RUN apk update && apk add git

RUN npm install -g expo-cli --allow-root --unsafe-perm=true 

WORKDIR /app
COPY . /app

ENV NODE_ENV development
RUN for attempt in $(seq 1 100); do yarn install --ignore-scripts --frozen-lockfile --ignore-optional && break; done
RUN npm rebuild

ENV NODE_ENV production
RUN expo build:web --no-pwa

# Deployment image
FROM nginx:1.19.1

LABEL version = "App server"

COPY --from=builder /app/web-build /usr/share/nginx/html

EXPOSE 80
EXPOSE 443

```

Basically, to summarize: when you yarn install expo with NODE_ENV = production, you're not getting the development dependencies, required for building your app. The error you get is
`Failed to read config at: /app/app.config.js`
The actual error is 
`Missing dependency babel-preset-expo` or something like that. But in order to figure this out you have to either not be a dumbass like me or shell into the container to console.log the error directly in expo getConfig.js

It should not be that hard to identify a simple mistake

**Comment by EvanBacon** [comment]
Maybe fixed in #2625 ?

**Comment by EvanBacon** [comment]
fixed in https://github.com/expo/expo-cli/pull/2656

**Comment by ShaneMcNamara** [comment]
By the way, I'm still seeing this issue with `expo install` and `app.config.js`.

```
          - npm install -g --production=false expo-cli
          - npm install
```
Works. But this:
```
          - npm install -g --production=false expo-cli
          - expo install
```

does not work.
