### ISSUE TITLE
expo start with @expo/dev-server in bare project starts with bare target (expected: managed)

### ISSUE THREAD

**Issue by ramicaza** [expo/expo-cli#3005]
## Description
Setting EXPO_USE_DEV_SERVER=true and using a custom font as per [this guide](https://docs.expo.io/guides/using-custom-fonts/) results in an 'unrecognized font family' error when running the EXPO CLIENT inside of a bare workflow project. (This might also happen in a managed workflow project but I haven't tested that).

## Environment

Expo CLI 4.0.11 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      npm: 6.14.9 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.3 => 0.63.3 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.11
    Expo Workflow: bare

iOS Simulator, iPhone 11, iOS 14.2

## Expected Behavior
Custom fonts work

## Observed Behavior
Custom fonts cause red error screen.  When you dismiss the error screen things still work but the fonts do not.

For some reason when setting EXPO_USE_DEV_SERVER=true, I can't get any console.log, console.warn, or console.error output to show up in the terminal.  The only way i know something is going wrong is when console.error results in the big red screen.

## Reproducible Demo

1. Run expo init
2. Choose bare-workflow minimal js template app
3. Add code for custom (not google) font as per [this guide](https://docs.expo.io/guides/using-custom-fonts/)
4. export EXPO_USE_DEV_SERVER=true
5. Run expo start and observe the error

**Comment by brentvatne** [comment]
hi @ramicaza! please provide a minimal reproducible example that we can clone and run, as per https://stackoverflow.com/help/minimal-reproducible-example

**Comment by brentvatne** [comment]
also, are you initializing a bare project with the intention of using the expo client alongside it?

i believe you can resolve this issue by using `EXPO_USE_DEV_SERVER=1 EXPO_TARGET=managed expo start` - to be explicit that you want to use expo client to open the project.

**Comment by ramicaza** [comment]
Thanks for the super fast response @brentvatne!  You were correct in that I just needed to set the EXPO_TARGET=managed.  I recommend that someone on the expo team pastes that exact command into [this guide](https://docs.expo.io/bare/using-expo-client/).  I followed that guide when attempting to set up the client to work with my bare-workflow app.  Hopefully that saves some people from the headache our team went through.

**Comment by brentvatne** [comment]
thanks for letting us know about this! i'll look into how dev server impacts the default behavior here

**Comment by brentvatne** [comment]
this should be resolved in the latest expo-cli version, thanks to https://github.com/expo/expo-cli/pull/3037

to summarize, we now default to managed workflow configuration when you run `expo start`, even in bare projects

**Comment by benfontan** [comment]
I am still having that `Unrecognized font family` with expo-cli 4.3.2.

> i believe you can resolve this issue by using EXPO_USE_DEV_SERVER=1 EXPO_TARGET=managed expo start - to be explicit that you want to use expo client to open the project.

This works for me and solves the problem but we should not have to do this anymore, right?
I see that the changes from #3037 you mentioned were overwritten by an important refactor on the packages/expo-cli/src/commands/start.ts. 

If I install expo-cli 4.1.6, I don't need to force EXPO_TARGET=managed.

**Comment by brentvatne** [comment]
@benfontan - probably related to a custom metro.config.js that overrides sourceExts and doesn't extend the expo metro config https://docs.expo.io/guides/customizing-metro/

**Comment by benfontan** [comment]
@brentvatne Thanks. Do you think expo-cli 4.1.6 would work in that case?
Indeed, I used a custom metro config for svg but it is extending the expo metro config.

```js
const { getDefaultConfig } = require('@expo/metro-config');
const defaultConfig = getDefaultConfig(__dirname);
module.exports = {
	transformer: {
		assetPlugins: ['expo-asset/tools/hashAssetFiles'],
		babelTransformerPath: require.resolve('react-native-svg-transformer')
	},
	resolver: {
		assetExts: [
			...defaultConfig.resolver.assetExts.filter((ext) => ext !== 'svg')
		],
		sourceExts: [...defaultConfig.resolver.sourceExts, 'svg']
	}
};
```
And with the exact same metro config, expo-cli 4.1.6 works (no unrecognized font issue) but the 4.3.2 doesn't.
