### ISSUE TITLE
expo-cli v5 breaks ignite-cli with "Something went wrong while downloading and extracting the template."

### ISSUE THREAD

**Issue by jamonholmgren** [expo/expo-cli#4423]
### Summary

Ignite CLI has had a hardcoded dependency on `expo-cli@4`, so I'm working on bumping that to expo-cli@5.

However, I'm getting this error:

```
Error downloading and extracting template package: Error: npm exited with non-zero code: 1
✖ Something went wrong while downloading and extracting the template.
```

Ignite uses a local Expo-compatible template.

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.1 - /opt/homebrew/opt/node@14/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 6.14.16 - /opt/homebrew/opt/node@14/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.9
    Expo Workflow: managed
```

Ignite CLI doctor:

```
System
  platform           darwin
  arch               arm64
  cpu                10 cores     Apple M1 Max
  directory          Temp         /Users/jh/Code/Temp

JavaScript (and globally-installed packages)
  node                            14.19.1      /opt/homebrew/opt/node@14/bin/node
  npm                             6.14.16      /opt/homebrew/opt/node@14/bin/npm
    eas-cli                       0.52.0
    expo-cli                      5.4.9
    firebase-tools                11.1.0
    ios-deploy                    1.11.4
    npm                           8.11.0
  yarn                            1.22.19      /opt/homebrew/bin/yarn
    create-react-native-library   0.20.1
  pnpm                            -            not installed
  expo                            -            not installed

Ignite
  ignite-cli         7.10.10      /opt/homebrew/bin/ignite
  ignite src         src          /Users/jh/Code/ignite-cli/src

Android
  java               11.0.14      /Users/jh/.sdkman/candidates/java/current/bin/java
  android home       -            /Users/jh/Library/Android/sdk

iOS
  xcode              13.4.1
  cocoapods          1.11.3       /opt/homebrew/bin/pod
```

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

```
EXPO_DEBUG=true npx expo-cli init Expotester2 --template /Users/jh/Code/ignite-cli/boilerplate@/Users/jh/Code/ignite-cli/boilerplate
Using template: /Users/jh/Code/ignite-cli/boilerplate@/Users/jh/Code/ignite-cli/boilerplate@/Users/jh/Code/ignite-cli/boilerplate@/Users/jh/Code/ignite-cli/boilerplate
- Downloading template.
Looking for tarball for /Users/jh/Code/ignite-cli/boilerplate@/Users/jh/Code/ignite-cli/boilerplate@/Users/jh/Code/ignite-cli/boilerplate@/Users/jh/Code/ignite-cli/boilerplate in /Users/jh/.expo/template-cache...
Run: npm pack /Users/jh/Code/ignite-cli/boilerplate@/Users/jh/Code/ignite-cli/boilerplate@/Users/jh/Code/ignite-cli/boilerplate@/Users/jh/Code/ignite-cli/boilerplate --dry-run
Error downloading and extracting template package: Error: npm exited with non-zero code: 1
- Downloading template.
✖ Something went wrong while downloading and extracting the template.

Can't read JSON file: /Users/jh/Code/Temp/Expotester2/app.json
└─ Cause: Error: ENOENT: no such file or directory, open '/Users/jh/Code/Temp/Expotester2/app.json'
    ├─ readAsync /opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/json-file/src/JsonFile.ts:158:13
    ├─ extractAndPrepareTemplateAppAsync /opt/homebrew/lib/node_modules/expo-cli/src/commands/utils/extractTemplateAppAsync.ts:25:25
    └─ actionAsync /opt/homebrew/lib/node_modules/expo-cli/src/commands/initAsync.ts:287:19
```

(note that the "can't read JSON file" is just a result of the earlier error -- the folder is empty)

### Reproducible demo or steps to reproduce from a blank project

```
git clone https://github.com/infinitered/ignite.git
EXPO_DEBUG=true npx expo-cli init Testexpo6 --template ./ignite/boilerplate
```

This should be all you need to do to see the error.

**Comment by jamonholmgren** [comment]
Note that the CI failure is here:

https://app.circleci.com/pipelines/github/infinitered/ignite/1068/workflows/9e8e8e87-6ac0-4d7a-800d-e56e28b33ca2/jobs/1447

**Comment by kbrandwijk** [comment]
This has been addressed in the recent `expo-cli` release as well as in `create-expo-app`.

**Comment by brodia10** [comment]
> This has been addressed in the recent `expo-cli` release as well as in `create-expo-app`.

I'm still getting this error using the latest versions of `expo-cli` and `node`.
<img width="776" alt="image" src="https://user-images.githubusercontent.com/29584063/182084857-2f81c55f-6457-4f46-bec9-59ab7c883d1b.png">

**Comment by Ps00007** [comment]
> > This has been addressed in the recent `expo-cli` release as well as in `create-expo-app`.
> 
> I'm still getting this error using the latest versions of `expo-cli` and `node`. <img alt="image" width="776" src="https://user-images.githubusercontent.com/29584063/182084857-2f81c55f-6457-4f46-bec9-59ab7c883d1b.png">


Any Updatez?
