### ISSUE TITLE
expo start Error: Non-fatal error updating development session API: FetchError: request to https://api.expo.dev/v2/development-sessions/notify-alive failed, reason: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by camnpr** [expo/expo-cli#4515]
### Summary

i update expo from 45 to 46.
`expo start` happen error.

### Environment

```bash
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.17134
    Binaries:
      Node: 14.17.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - ~\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.0.0.0 AI-171.4408382
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2
      expo: ~46.0.6 => 46.0.6
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
      react-native-web: 0.18.7 => 0.18.7
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

chrome web

### Error output

```txt
Metro waiting on exp://192.168.1.3:19000
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Web is waiting on http://localhost:19006

› Press a │ open Android
› Press w │ open web

› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

› Open in the web browser...
› Press ? │ show all commands
Non-fatal error updating development session API: FetchError: request to https://api.expo.dev/v2/development-sessions/notify-alive failed, reason: Client network socket disconnected before secure TLS connection was established
Non-fatal error updating development session API: FetchError: request to https://api.expo.dev/v2/development-sessions/notify-alive failed, reason: socket hang up
Web Bundling failed 76661ms
Unable to resolve "./Libraries/Components/DatePicker/DatePickerIOS" from "node_modules\react-native\index.js"
Web Bundling failed 2357ms
Unable to resolve "./Libraries/Components/DatePicker/DatePickerIOS" from "node_modules\react-native\index.js"
```

### Reproducible demo or steps to reproduce from a blank project

Demo: [https://snack.expo.dev/@camnpr/expoupgrade46](https://snack.expo.dev/@camnpr/expoupgrade46)

**Comment by GuilhermeZanetti** [comment]
Same issue

**Comment by KieQuang** [comment]
+1

**Comment by claudioovp** [comment]
+1

**Comment by jwAndroid** [comment]
+1

**Comment by oscaralderete** [comment]
+1

**Comment by shuence** [comment]
+1

**Comment by FridayCandour** [comment]
same issue over here

**Comment by samloba** [comment]
same here

**Comment by ser-emejia** [comment]
Same here

**Comment by Ariong-hub** [comment]
same on issue here on android

**Comment by alxndr777** [comment]
+1

**Comment by unipine** [comment]
+1

**Comment by EvanBacon** [comment]
A fix was landed in https://github.com/expo/expo/pull/19038 and should be available in the latest CLI (beta). This is only a warning and not a fatal error. The warning was just not printed in earlier versions, we've gone back to not printing the warning.

**Comment by FROLIANI** [comment]
Non-fatal error updating development session API: FetchError: request to https://api.expo.dev/v2/development-sessions/notify-alive failed, reason: getaddrinfo ENOTFOUND api.expo.dev



i still get error
