### ISSUE TITLE
@expo/webpack-config: webpack bundling fails with alternative entrypoints

### ISSUE THREAD

**Issue by danadajian** [expo/expo-cli#4624]
### Summary

I am trying to use [Cypress component testing](https://docs.cypress.io/guides/component-testing/overview) with expo (for web components), but the `app` entrypoint is not available in the webpack-manifest-plugin, and only the `main` entrypoint exists. This results in a "cannot read property of undefined" error on [this line](https://github.com/expo/expo-cli/blob/main/packages/webpack-config/src/webpack.config.ts#L522). There does not appear to be a workaround for this issue using any configuration.

I have raised #4610 which resolves this easily!

### Environment

OS: macOS 13.1
`@expo/webpack-config`: v0.17.3
`react-native`: v0.70.5

### Please specify your device/emulator/simulator platform, model and version

n/a

### Error output

```bash
✖ ｢wdm｣: TypeError: Cannot read properties of undefined (reading 'filter')
    at Object.generate (/Users/danadajian/WebstormProjects/LastDram/webpack-config/webpack/webpack.config.js:418:65)
    at ManifestPlugin.<anonymous> (/Users/danadajian/WebstormProjects/LastDram/node_modules/webpack-manifest-plugin/lib/plugin.js:199:28)
    at _next2 (eval at create (/Users/danadajian/WebstormProjects/LastDram/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at eval (eval at create (/Users/danadajian/WebstormProjects/LastDram/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
```

### Reproducible demo or steps to reproduce from a blank project

1. Set up a react-native + expo project
2. Set up a custom webpack config for the Cypress component test runner. Here's mine: 
```js
module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync({ ...env, mode: 'production' }, argv);

  // Process any JS outside of the app with Babel.
  // Unlike the application JS, we only compile the standard ES features.
  config.module.rules.push({
    test: /\.(js|mjs|tsx?)$/,
    exclude: /@babel(?:\/|\\{1,2})runtime/,
    loader: require.resolve('babel-loader'),
    options: {
      babelrc: false,
      configFile: false,
      compact: false,
      presets: [
        [require.resolve('babel-preset-react-app/dependencies'), { helpers: true }],
        '@babel/preset-react',
        '@babel/preset-typescript'
      ],
      cacheDirectory: true,
      // See #6846 for context on why cacheCompression is disabled
      cacheCompression: false,

      // Babel sourcemaps are needed for debugging into node_modules
      // code.  Without the options below, debuggers like VSCode
      // show incorrect code and set breakpoints on the wrong lines.
      sourceMaps: true,
      inputSourceMap: true
    }
  });

  config.module.rules.push({
    test: /\.mjs$/,
    include: /node_modules/,
    type: 'javascript/auto'
  });

  return config;
};
```
3. Run a Cypress test and watch compilation fail with the above error.

**Comment by inform880** [comment]
Is there a workaround for this bug?

**Comment by danadajian** [comment]
I have not been able to find a workaround. I think adding an optional chain as I did in #4610 is the easiest solution!

**Comment by danadajian** [comment]
This has been resolved by the [webpack 5 upgrade](https://github.com/expo/expo-cli/pull/3763)! 🥳

**Comment by g-wozniak** [comment]
Still is not fixed. :|

```
Your configFile threw an error from: cypress.config.js
We stopped running your tests because your config file crashed.
Error: @expo/webpack-config requires a valid `mode` string which should be one of: development, production, none
```

"expo": "~48.0.15"
"@expo/webpack-config": "^18.0.1"
"cypress": "^12.13.0"
