### ISSUE TITLE
"Could not access packager status"

### ISSUE THREAD

**Issue by acomito** [expo/expo-cli#52]
## Description

- I download expo expo-cli
- I run expo init
- project gets generated, etc.
- I run `yarn start`
- I see:

```
[09:56:32] Starting project at /Users/me/testing-expo
[09:56:34] Starting Metro Bundler on port 19003.
[09:56:34] Metro Bundler ready.
[09:57:03] Could not access packager status at http://localhost:19003/status. Are you sure the packager is running and reachable?
[09:57:03] Set EXPO_DEBUG=true in your env to view the stack trace.
```

## Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.12.0
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/heyned_tester-49231240-7d93-4f44-b26f-d6f0a7784b07.tar.gz

Potentially related:

- https://forums.expo.io/t/major-issues-with-expo-best-way-to-100-uninstall-expo-react-native-and-then-re-install/14212
- 
- https://stackoverflow.com/questions/52494855/reactnative-set-expo-debug-issue
- https://forums.expo.io/t/react-native-set-expo-debug-true/14163
- https://github.com/expo/expo/issues/1381
- https://stackoverflow.com/questions/52112016/react-native-crna-packager-stops-running
- https://stackoverflow.com/questions/52514526/uses-expo-start-instead-of-npm-start

## Reproducible Demo

This is just with a fresh expo-cli install and fresh project from expo-cli

**Comment by acomito** [comment]
possible duplicate of https://github.com/expo/expo-cli/issues/50

**Comment by brukh** [comment]
I am having the same issue. And I also see the packager is running at `http://localhost:19001/status`.

I updated CRNA and created a new project and ran into the same issue. 

There was an instance where I ran `expo start --lan` and the command ran successfully but I couldn't reproduce this result.

**Comment by angyy10** [comment]
i solved by clearing NPM cache (npm cache clean --force)
https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352

**Comment by acomito** [comment]
I've changed node versions, uninstall/reinstalled expo-cli, yarn, npm, clean caches, reset watchman but no luck. I'm bummed out.

I did try and `expo start --lan` and my terminal got one step further before failing... went from

```
[09:45:08] Starting Metro Bundler on port 19001.
[09:45:08] Metro Bundler ready.
[09:45:37] Could not access packager status at http://localhost:19001/status. Are you sure the packager is running and reachable?
[09:45:37] Set EXPO_DEBUG=true in your env to view the stack trace.
```

to 

```
[09:45:50] Starting Metro Bundler on port 19001.
[09:45:50] Metro Bundler ready.
[09:46:04] ::1 - - [28/Sep/2018:13:46:04 +0000] "GET /favicon.ico HTTP/1.1" 404 150 "http://localhost:19001/status" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
[09:46:19] Could not access packager status at http://localhost:19001/status. Are you sure the packager is running and reachable?
[09:46:19] Set EXPO_DEBUG=true in your env to view the stack trace.
```

**Comment by calvinlang** [comment]
I'm definitely having the same issues as everyone else

**Comment by ryanlozon** [comment]
I'm in the same boat

**Comment by miguelrs** [comment]
👍 I'm also getting this error always - I'm about to give up 😞 
I can't figure out a pattern, it just randomly works sometimes - I did notice it seems to be more likely to work when the `EXPO_DEBUG` env variable is set, but still fails most of the times...

**Comment by aminoche** [comment]
I am having this issue too.  😢

**Comment by leventebalogh** [comment]
I am having the same issue as well. 

**Workaround that worked for me:**
```bash
$ npm uninstall -g expo-cli
$ npm cache clean --force
$ npm install -g expo-cli  
```

**Comment by sant3001** [comment]
This solved the problem for me (using Mac). Type:

    sudo vim /etc/hosts
and insert your password to edit the hosts file and insert this line to the end of the file:

    127.0.0.1    localhost

**Comment by aminoche** [comment]
Somethings that I try when this happens.

1. Open a browser window at http://localhost:19002/
2. Open the Expo app on my phone
3. Open the Expo app on my phone simulator
4. Run expo start --tunnel in case it's a LAN issue
5. ...close everything and reopen everything.

...wish there was some more description on how to proceed with this error.

**Comment by cloeffler** [comment]
I am getting the same thing on my Mac, i try to make a new project with expo init , then do expo start. Then
[09:42:07] Starting project at /Users/user/Documents/Project
[09:44:12] Starting Metro Bundler on port 19001.
[09:44:13] Could not access packager status at http://localhost:19001/status. Are you sure the packager is running and reachable?
[09:44:13] Set EXPO_DEBUG=true in your env to view the stack trace.

i dont know mabie a problem with the new version of expo-cli?

**Comment by cloeffler** [comment]
i can access packager status from my browser, but expo-cli cant?

**Comment by aki77** [comment]
Clean installation of Mojave solved the same problem. (using Mac)

**Comment by cloeffler** [comment]
are you reffering to the whole operating system?

**Comment by leventebalogh** [comment]
> are you reffering to the whole operating system?

I hope not, that would be a bit of an overkill 😄

**Comment by deot** [comment]
The proxy server is open？

**Comment by laurentsmohr** [comment]
@sant3001 solution did it for me

**Comment by silenjs** [comment]
When  running on another computer(mac):
...
Running logs show:
Expo DevTools is running at http://localhost:19004
...
So,i guess：
vim /etc/hosts
127.0.0.1 localhost
---
it worked!

**Comment by LucasGarcez** [comment]
I had the same problem when I logged in with my expo account via prompt, 'expo login', and then I ran the 'expo start' command.
Then I closed the prompt and ran 'expo start', it worked correctly.

OS: Windows 10

**Comment by jakeprins** [comment]
Same as @LucasGarcez I had to use 'expo login' to first login again after I updated expo-cli. Tried everything else but this was the only thing that worked for me.

**Comment by LucasGarcez** [comment]
I have had this problem many times and each one has been corrected in a different way, but the last time nothing worked. I spent many hours trying to find some solution and even looked inside the expo-cli source code.
I am new to JS and RN, so I do not understand the code very well, but I found the function that returns this error message in C: \ Users \ {UserName} \ AppData \ Roaming \ npm \ node_modules \ expo-cli \ node_modules \ xdl \ build \ Project.js

```javascript
const timeoutPromise = new Promise (function (resolve, reject) {
      return setTimeout (function () {
        return reject (new Error (`Could not access packager status at $ {statusUrl}. Are you sure the packager is running and reachable?));
      }, WAIT_FOR_PACKAGER_TIMEOUT);
    });
```

So I modified the WAIT_FOR_PACKAGER_TIMEOUT constant to an extremely large value:
I set: 
```javascript
const WAIT_FOR_PACKAGER_TIMEOUT = 5000 * 1000;
```

 In this way I could work on the project for the time determined in WAIT_FOR_PACKAGER_TIMEOUT until Expo throws the error.

**I'm aware that this is not a solution** , I really think there is a bug in expo-cli or something like that. But I have term in my project and after several days with this recurring and unsolvable error this was the only way I found to keep working on my project. 

Maybe I can help someone in a situation similar to mine.

**Comment by acomito** [comment]
Update: still can't get it working.

Oddly, I can't seem to uninstall expo-cli.

**Comment by LucasGarcez** [comment]
> 
> 
> Update: still can't get it working.
> 
> Oddly, I can't seem to uninstall expo-cli.

@acomito[ with npm](https://docs.npmjs.com/cli/uninstall): `npm uninstall -g expo-cli`

verify that the expo-cli is installed on another package manager such as yarn. If ever you installed via yarn there are otherd expo-cli packages in the yarn files.

**Comment by jakeprins** [comment]
@acomito try `npm install -g expo-cli`, then logging out  `expo logout` and logging in `expo login` before you run `expo start`

**Comment by elhoussine** [comment]
`expo start --tunnel` fixed it for me

**Comment by korede360** [comment]
Hello everyone. Kindly try `expo start --tunnel` or `expo start --lan`. This worked for me.

**Comment by poserr** [comment]
> Hello everyone. Kindly try `expo start --tunnel` or `expo start --lan`. This worked for me.

Not for me, unfortunately : 



```
expo start --lan
[12:17:41] Starting project at ...
[12:17:42] Expo DevTools is running at http://localhost:19002
[12:17:42] Opening DevTools in the browser... (press shift-d to disable)
[12:17:48] Starting Metro Bundler on port 19001.
[12:18:15] Could not access packager status at http://127.0.0.1:19001/status. Are you sure the packager is running and reachable?
```

**Comment by korede360** [comment]
@poserr Try running the normal `expo start` after that. I'm now proper confused. I'm not even sure if it's an issue with `/etc/hosts/`, or just a tunnel or LAN issue.

**Comment by poserr** [comment]
@korede360 I did, but result is the same:

```
expo start
[16:00:26] Starting project at /awww/workspace/jl-new/jl-rn
[16:00:26] Expo DevTools is running at http://localhost:19002
[16:00:26] Opening DevTools in the browser... (press shift-d to disable)

[16:00:32] Starting Metro Bundler on port 19001.
[16:00:59] Could not access packager status at http://127.0.0.1:19001/status. Are you sure the packager is running and reachable?
[16:00:59] Error: Could not access packager status at http://127.0.0.1:19001/status. Are you sure the packager is running and reachable?
    at Timeout._onTimeout (/xdl@51.4.8/src/Project.js:1511:11)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

I don't see any difference, apart from 127.0.0.1 vs localhost - but since I have MAMP working, I guess it resolves requests to localhost anyway.

**Comment by jakeprins** [comment]
Damn, having the same issue again. This time, none of all the suggestions is working for me. 😕

**Comment by lewatt23** [comment]
Having the same  problem  any help  tried all the above  , even updated to  the latest  expo-cli  , please someone  help  is been days can even  code something ....

**Comment by Idimma** [comment]
> Having the same problem any help tried all the above , even updated to the latest expo-cli , please someone help is been days can't even code something ....

You keep trying it... it will work 

or you try expo start --lan

**Comment by korede360** [comment]
Is any core team member looking into this issue? I'm legit considering going back to pure React Native. It would be nice if a core contributor could state the cause and/or status of this issue. Thanks to everyone for sharing their workarounds. It's just that none of them work permanently (at least, not for me).

**Comment by fson** [comment]
@korede360 which version of Expo CLI are you using?

When starting Expo CLI with `expo start`, it starts the Metro bundler and then waits until it's running by polling its `/status` endpoint. The "Could not access packager status" error happens when, after polling for 30 seconds, Expo CLI hasn't received a successful response from the bundler. This can happen for multiple reasons.

One of the reasons was that some people did `localhost` defined in their `/etc/hosts` file, which caused the requests to `http://localhost:<bundler-port>/status` fail. We fixed last month in `expo-cli@2.2.3` by changing the status checks to use the loopback IP address `127.0.01` instead of `localhost`. (This is also why some people suggested using the `--lan` option since that also forces the URLs to use the IP address of the computer.)

But since some people are still having this problem, it seems that it can happen for other reasons than not being able to resolve `localhost`. I am looking into this now. Since it seems to only happen in a certain scenario / networking setup, the only way to find out the real cause might be to add more logging to see why Metro doesn't start or the CLI is not able to connect to it.

**Comment by korede360** [comment]
Thanks @fson. I'm using `expo-cli@2.5.0`. (I think 2.6.0 was just released 4 hours ago). I there any way to make `expo start` return verbose output, so I can see where the error might be coming from?

**Comment by poserr** [comment]
I have updated to 2.6.0 and have the same issue, unfortunately: 

```
 expo start
[11:46:24] Starting project at /awww/workspace/jl-new/jl-rn
[11:46:35] Expo DevTools is running at http://localhost:19002
[11:46:35] Opening DevTools in the browser... (press shift-d to disable)
[11:47:04] Starting Metro Bundler on port 19001.
[11:47:22] Could not access packager status at http://127.0.0.1:19001/status. Are you sure the packager is running and reachable?
[11:47:22] Error: Could not access packager status at http://127.0.0.1:19001/status. Are you sure the packager is running and reachable?
    at Timeout._onTimeout (/xdl@52.0.0/src/Project.js:1598:11)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

I can only add that I have MAMP PRO working and running and I am behind corporate proxy. (normally none of these should be a problem)

**Comment by jakeprins** [comment]
I recently updated to expo `^31.0.4` and `expo-cli 2.4.1` and now I almost never experience the problem anymore.

**Comment by lewatt23** [comment]
Updated to  expo 2.6.0 and things seems  to  be  fine . thanks  expo team 👍

**Comment by korede360** [comment]
@fson, I've not had this issue since I updated to 2.6.0. Thanks to the Expo team for fixing.

**Comment by poserr** [comment]
> I have updated to 2.6.0 and have the same issue, unfortunately:
> 
> ```
>  expo start
> [11:46:24] Starting project at /awww/workspace/jl-new/jl-rn
> [11:46:35] Expo DevTools is running at http://localhost:19002
> [11:46:35] Opening DevTools in the browser... (press shift-d to disable)
> [11:47:04] Starting Metro Bundler on port 19001.
> [11:47:22] Could not access packager status at http://127.0.0.1:19001/status. Are you sure the packager is running and reachable?
> [11:47:22] Error: Could not access packager status at http://127.0.0.1:19001/status. Are you sure the packager is running and reachable?
>     at Timeout._onTimeout (/xdl@52.0.0/src/Project.js:1598:11)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)
> ```
> I can only add that I have MAMP PRO working and running and I am behind corporate proxy. (normally none of these should be a problem)

after removing PROXY environment variables everything started to work fine.

**Comment by fson** [comment]
Hi all, `expo-cli@2.6.1` has some additional logging in case things go wrong and also disables the proxy for the local HTTP call to check the status. If you're still having this issue please upgrade with `npm install -g expo-cli` and comment here, if that helped!

**Comment by robertcreaner** [comment]
Remove any special characters from your folder structure 

**/Users/me/testing-expo** should be **/Users/me/TestingExpo**

**Comment by robertcreaner** [comment]
Experiencing this issue yet again with expo-cli@2.6.14. In fact, I can't even open the Expo app in my simulator any more. It gets frozen on the splash screen with the Expo logo.

**Comment by fson** [comment]
@robertcreaner please let us know which error message is printed by Expo CLI and the output from `expo diagnostics`.

**Comment by seaserapp** [comment]
just add it to the PATH: C:\Windows\System32 and start cmd as Administrator

**Comment by wcisco17** [comment]
Hey guys, I'm running into the same issue again and again. After running 
`npm unistall -g expo-cli` and reinstalling it I still get this error: 

`Could not get status from Metro bundler. connect ECONNREFUSED 127.0.0.1:19001`
`Connecting to Metro bundler failed.`


Then the Program then terminates..  


and that's every time I run `expo start --tunnel` or `expo start --lan` 

Is there any work around or better yet permanent fix for this issue? Without having to reinstall and install the expo cli every time I start my project

**Comment by cloeffler** [comment]
i found the problem for me was that my crappy mac mini was to slow at opening expo, so it would timeout after 30 sec and give up. Giving me the..

Could not get status from Metro bundler. connect ECONNREFUSED 127.0.0.1:19001
Connecting to Metro bundler failed.

**Comment by korede360** [comment]
I can confirm that this issue still exists. Sometimes `expo start` with `--lan` or  `--tunnel` works, but most times, I can't run my Expo app. Does this issue occur because of the speed of the computer (@cloeffler) or because of the /etc/hosts file? This issue is slowing down my progress at work. Thanks.

My `expo diagnostics`:
```
Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
      Yarn: 1.12.3 - ~/.npm-global/bin/yarn
      npm: 6.5.0-next.0 - ~/.nvm/versions/node/v11.6.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.1
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.0.9
```

**Comment by korede360** [comment]
If it helps, I'm facing this issue on a 2012 MacBook Pro 13" (4GB RAM). I'm not sure if it has anything to do with the speed at which the computer is able to start Metro Bundler (@cloeffler, can you confirm?). @fson, Is there any way to increase the time that the program spends waiting for Metro Bundler to start? Thanks for your help, everyone.

**Comment by zaytrix** [comment]
Hello, I'm facing a similar issue. Sometimes `expo start` works, sometimes it just doesn't and just gives me `connect ECONNREFUSED 127.0.0.1:19001`. The variations of `expo start --lan` and `expo start --tunnel` don't seem to affect this outcome.
  
Here's the full output of `expo start` with `EXPO_DEBUG=true`:
```
[11:32:24] Could not get status from Metro bundler. connect ECONNREFUSED 127.0.0.1:19001
[11:32:24] Connecting to Metro bundler failed.
[11:32:24] Error: Connecting to Metro bundler failed.
    at /xdl@52.1.0/src/Project.js:1375:11
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/build/Project.js:2236:191)
    at /usr/local/lib/node_modules/expo-cli/node_modules/xdl/build/Project.js:2236:402
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

Here's my `expo diagnostics`:
```
  Expo CLI 2.7.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.0.9
    npmGlobalPackages:
      expo-cli: 2.7.0
```

Similar to @cloeffler, I'm running this on a old 2014 Mac mini, with 4GB of RAM and 1.4GHz i5 processor, if that helps.

**Comment by korede360** [comment]
Hey, @zaytrix @cloeffler quick update... I upgraded my RAM to a 10GB (8+2)GB one, cleared my yarn cache, deleted and reinstalled `expo-cli` and I hardly ever experience this issue anymore. Another hack you could try is to make sure your browser is already open, to prevent delay in starting Expo DevTools, and then start Expo with `expo start -c`

**Comment by zaytrix** [comment]
Unfortunately, I am unable to upgrade my RAM, and I had already been preventing Expo DevTools from opening up. Clearing the yarn cache and deleting and reinstalling `expo-cli` does not seem to help.  With an older project that uses `react-native-scripts` instead of `expo-cli`, this issue never occurs and runs just fine on the same computer.

**Comment by zaytrix** [comment]
Additionally, sometimes when i restart the Metro Bundler by typing `r`, (after `expo start` had already worked) I get this message:
```
UnhandledPromiseRejectionWarning: Error: Connecting to Metro bundler failed.
    at /xdl@52.1.0/src/Project.js:1375:11
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/build/Project.js:2236:191)
    at /usr/local/lib/node_modules/expo-cli/node_modules/xdl/build/Project.js:2236:402
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:44147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 812)
(node:44147) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

However when that happens, it seems to try again automatically until it finally works, which is nice.

**Comment by korede360** [comment]
@fson Can the 30 second timeout be increased? I perceive that slower computers take longer than that to start Metro Bundler. Thanks.

**Comment by jugbeep** [comment]
@sant3001 Your solution worked for me. I had add the address to 127.0.0.2 also.

**Comment by guoze-292** [comment]
Hi all, I still have this problem and I tried every method mentioned above but never got to work. Any new ideas?

**Comment by Akkujvl** [comment]
Hello all, I had same issue. Fixed by updating expo cli, removing  .expo folder and expo start.

**Comment by zaytrix** [comment]
I do believe that the cause of the issue I've been running into is due to limited RAM. Whether the cause is the amount of available RAM itself or the slowdown that occurs when nearing RAM capacity, the issue seems to resolve itself after I free up enough RAM by ending processes that are taking up a significant amount of memory. It's not a great solution but I don't really have any other choice.

**Comment by quadsurf** [comment]
I doubt the majority of this issue is a RAM issue @zaytrix @korede360 ... it may be a small contributing factor, but I'm running 16G of RAM on a 2018 MacBook Pro, and still getting this same issue, even after a fresh system reboot.

**Comment by tolulope-od** [comment]
Fixed this issue by just restarting my computer

**Comment by zaytrix** [comment]
@quadsurf You may be right about that, it may have just been coincidence that it worked after I freed up RAM, since if I just keep trying it will will work eventually. The real problem is that it may take as long as an hour before it decides to not fail on me, which is not great when I'm trying to use this at work.

**Comment by zaytrix** [comment]
I'm having more success getting it to work when I run `expo start`, immediately ctrl+c, then running `expo start` again. Usually starts up on the first/second try when doing that. Not sure how to configure the yarn start script to do that, but it would be handy.
This trick brought to you by this comment: https://github.com/expo/expo/issues/2115#issuecomment-416022745

**Comment by diegolaciar** [comment]
+1  Just restart the Mac

**Comment by diegolaciar** [comment]
I did the restart and worked, but later the day the issue rise again, so I restarted my mac.

Finally I did this

```bash
ps | grep -i  metro
```
and killed all the metro process instances.

expo start and the issue was gone.....

**Comment by DiegoBneiNoah** [comment]
I have had the same situation. I entered `/etc/hosts` and added `127.0.0.1:1900 localhost`. And I was able to use `yarn start`. I'm not sure if I previously had using `expo start --lan` influenced what I later changed '/etc/hosts` to do so. But after all, I was able to run the app and compile JavaBundle...

**Comment by gogulnathv** [comment]
This can usually happen when publishing without ever having run expo start, also it's a good idea to run rm -rf .expo to clear your local state

We can probably do a better job with this and intercept the error message to provide better feedback

[Link](https://github.com/expo/expo-cli/issues/949#issuecomment-541145007) -- Solution @cruzach

**Comment by sarangCV** [comment]
I think it's more of a windows Defender issue.. disabling reak time protects saved me.

**Comment by titogarcia** [comment]
The issue is in line 2059 of expo-cli/packages/xdl/src/Project.ts. The timeout is fixed to 30 seconds (300 retries every 100 ms). If your computer takes more than that, you're sold. Mine does.

```
await Promise.race([_waitForRunningAsync(projectRoot, `${packagerUrl}/status`), exitPromise]);
```

```
async function _waitForRunningAsync(
  projectRoot: string,
  url: string,
  retries: number = 300
): Promise<true> {
```

Could an proficient Expo developer fix this, please? Some kind of environment variable or configuration parameter?

Thanks!
Ernesto

**Comment by ViduraPrasangana** [comment]
Fixed by updating expo-cli to 3.20.9
