### ISSUE TITLE
optimize assets breaks CI

### ISSUE THREAD

**Issue by tonnenpinguin** [expo/expo-cli#578]
## Description
expo-cli 2.17.0 breaks CI pipelines by requiring user input to answer the "optimize assets now" question.

This was already reported by other users here: https://forums.expo.io/t/expo-cli-2-17-0-breaks-my-circleci-build-with-optimize-assets-question/22397/3

## Expected Behavior
expo cli does not expect user input when publishing in non-interactive mode / accepts command line argument to answer such questions.

## Observed Behavior
expo cli asks whether we want to optimize assets now and therefore breaks CI pipelines.

```
> expo publish --non-interactive --config=config/app.json

[12:13:18] It seems your assets have not been optimized yet.
[12:13:18] Input is required, but Expo CLI is in non-interactive mode.
Required input:
> Do you want to optimize assets now?
```

## Reproducible Demo

Run expo publish --non-interactive on a repo that has not been optimized yet.

**Comment by sergeichestakov** [comment]
Hey @tonnenpinguin,

Really sorry about the inconvenience! I just published the changes associated with #583 so you should be able to install the latest version of `expo-cli` which should fix this issue and allow for a `--non-interactive` flag for both `publish` and `optimize`.

I think in the future we will switch to a warning rather than a prompt, but it's helpful to have actual users use this feature to provide feedback and help us find a better workflow.

Let me know if you run into any more issues and I'll be happy to help.

Thanks,
Sergei

**Comment by amowu** [comment]
When I run `expo build:ios` of expo-cli@2.18.2, it still happens

**Comment by sergeichestakov** [comment]
Fixed in https://github.com/expo/expo-cli/pull/647
